# Generated by Django 6.0 on 2025-12-28 01:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100, verbose_name='Task name: ')),
                ('taskdescription', models.CharField(blank=True, max_length=400, null=True, verbose_name='Description and status(finished/todo/in progress)): ')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 28, 1, 13, 13, 6272, tzinfo=datetime.timezone.utc))),
                ('lastModified', models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 28, 1, 13, 13, 6286, tzinfo=datetime.timezone.utc))),
                ('tasklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='apptareas.page')),
            ],
        ),
    ]
