# Generated by Django 6.0 on 2025-12-13 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100, verbose_name='Task name: ')),
                ('taskdescription', models.CharField(blank=True, max_length=400, verbose_name='Description: ')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 13, 17, 58, 53, 118953, tzinfo=datetime.timezone.utc))),
                ('lastModified', models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 13, 17, 58, 53, 118967, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
