# Generated by Django 6.0 on 2025-12-13 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 13, 18, 35, 21, 78958, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='lastModified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 13, 18, 35, 21, 78972, tzinfo=datetime.timezone.utc)),
        ),
    ]
