# Generated by Django 6.0 on 2025-12-13 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptareas', '0002_alter_task_createdat_alter_task_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 13, 18, 43, 1, 175272, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='lastModified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 13, 18, 43, 1, 175286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskdescription',
            field=models.CharField(blank=True, max_length=400, verbose_name='Description and status(finished/todo/in progress)): '),
        ),
    ]
